# Generated by Django 3.1.2 on 2020-10-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('code', models.IntegerField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Emp',
            },
        ),
        migrations.RenameModel(
            old_name='Colleges',
            new_name='College',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.AlterModelOptions(
            name='college',
            options={'verbose_name_plural': 'College'},
        ),
    ]
